export const UNASSIGNED = 0;
export const HARVESTER = 1;
export const BUILDER = 2;
export const UPGRADER = 3;
export const REPAIRER = 4;

type TYPE_ROLE_UNASSIGNED = typeof UNASSIGNED;
type TYPE_ROLE_HARVESTER = typeof HARVESTER;
type TYPE_ROLE_BUILDER = typeof BUILDER;
type TYPE_ROLE_UPGRADER = typeof UPGRADER;
type TYPE_ROLE_REPAIRER = typeof REPAIRER;
export type Roles = TYPE_ROLE_UNASSIGNED | TYPE_ROLE_HARVESTER | TYPE_ROLE_BUILDER | TYPE_ROLE_UPGRADER | TYPE_ROLE_REPAIRER;
